telegram:
  admin: "Her72hbf" # Ваш telegram username, писать без @
  host: "api.telegram.org"
  token: "" # Ваш бот токен
  update_timeout: 60

web_server:
  addr: "0.0.0.0:8082"
  read_timeout: 60s
  write_timeout: 60s

vk_api:
  token: ""  # Ваш vk api серверный ключ

slog:
  env: "dev"
  output: "console"

migrations_path: "file://migrations"

storage:
  DB_HOST: "postgres"
  DB_PORT: 5432
  DB_NAME: "mydb"
  DB_USER: "user"
  DB_PASSWORD: "password"

file_storage:
  addr: "192.168.0.102:9000"  # Замените на свой ip host
  key_id: "minioadmin"
  secret_key: "minioadmin"

redis:
  addr: "redis:6379"
  password: ""
  DB: 1
