telegram:
  host: ""
  token: ":"
  update_timeout: 60

web_server:
  addr: "0.0.0.0:49500"
  read_timeout: 60s
  write_timeout: 60s

vk_api:
  token: ""

slog:
  env: "dev"
  output: "console"

migrations_path: "file://migrations"

storage:
  DB_HOST: "localhost"
  DB_PORT: 5432
  DB_NAME: "testdb"
  DB_USER: "username"
  DB_PASSWORD: "password"

file_storage:
  addr: ""
  key_id: "minioadmin"
  secret_key: "minioadmin"

redis:
  addr: "localhost:6379"
  password: ""
  DB: 1
